apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: muhammed-role
  namespace: muhammed
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muhammed-rolebinding
  namespace: muhammed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: muhammed-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: muhammed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: muhammed-clusterrolebinding
  namespace: muhammed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kurs1-developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: muhammed